# 抓取站点 masiro 真白萌，esj esj，lk 轻国，yuri 百合会，支持多站点例['esj', 'masiro']
sites: ['esj']
# 白名单，只会爬取白名单内的书籍，如果存在多个站点此项会无效，填入书籍地址或id具体格式见readme
white_list: []
# 登录账号密码或cookie 账密登录优先级高于cookie登录
login_info:
  esj:
    username: ''
    password: ''
    cookie: ''
  masiro:
    # 真白萌账密登录需要配置flaresolverr 请拉取此镜像alexfozor/flaresolverr:pr-1300-experimental 例http://127.0.0.1:8191/v1
    flaresolverr_url: ''
    username: ''
    password: ''
    # 真白萌cookie登录需要额外抓User-Agent
    cookie: ''
    useragent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'
  lk:
    username: ''
    password: ''
  yuri:
    cookie: ''
  fish:
    cookie: ''
# 开始页
start_page: 1
# 结束页 不建议一次抓取过多
end_page: 1
# 代理地址 仅支持http代理 例'http://127.0.0.1:1081' 注意esj只能挂非日韩节点的代理
proxy_url: ''
# 轻国或真白萌是否花费金币购买章节
is_purchase: true
# 章节花费上限，高于配置值的章节不购买
max_purchase: 100
# 生成epub时是否全局繁转简
convert_hans: true
# 定时执行设置 enabled定时开关hour时minute分
scheduler_config:
  enabled: false
  hour: 9
  minute: 30