from __future__ import annotations

from PySide6 import QtCore, QtWidgets
from src.services.text_catalog import get_text_catalog
from ui.bookshelf_panel import BookshelfPanel

TEXTS = get_text_catalog()


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle(TEXTS.get_text("window.title"))
        self.resize(1180, 760)
        self._build_ui()

    def _build_ui(self):
        central = QtWidgets.QWidget()
        self.setCentralWidget(central)
        root_layout = QtWidgets.QHBoxLayout(central)
        root_layout.setContentsMargins(12, 12, 12, 12)
        root_layout.setSpacing(12)

        root_layout.addWidget(self._build_form_panel(), 1)
        right_panel = QtWidgets.QWidget()
        right_layout = QtWidgets.QVBoxLayout(right_panel)
        right_layout.setContentsMargins(0, 0, 0, 0)
        right_layout.setSpacing(12)
        self.bookshelf_panel = BookshelfPanel()
        right_layout.addWidget(self.bookshelf_panel, 1)
        right_layout.addWidget(self._build_log_panel(), 1)
        root_layout.addWidget(right_panel, 1)

    def _build_form_panel(self) -> QtWidgets.QWidget:
        panel = QtWidgets.QScrollArea()
        panel.setWidgetResizable(True)
        content = QtWidgets.QWidget()
        panel.setWidget(content)
        layout = QtWidgets.QVBoxLayout(content)
        layout.setSpacing(12)

        intro = QtWidgets.QLabel(TEXTS.get_text("text.intro"))
        intro.setWordWrap(True)
        layout.addWidget(intro)

        task_group = QtWidgets.QGroupBox(TEXTS.get_text("group.task_settings"))
        task_layout = QtWidgets.QFormLayout(task_group)
        self.task_form_layout = task_layout
        task_layout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.site_combo = QtWidgets.QComboBox()
        self.site_combo.addItems(["esj", "masiro", "lk", "yuri"])
        self.task_mode_combo = QtWidgets.QComboBox()
        self.task_mode_combo.addItem(TEXTS.get_text("option.task_mode_single_link"), "single_link")
        self.task_mode_combo.addItem(TEXTS.get_text("option.task_mode_collection_page"), "collection_page")
        self.task_mode_combo.addItem(TEXTS.get_text("option.task_mode_page_range"), "page_range")
        self.task_name_edit = QtWidgets.QLineEdit()
        self.task_name_edit.setPlaceholderText(TEXTS.get_text("placeholder.task_name"))
        self.single_url_edit = QtWidgets.QLineEdit()
        self.single_url_edit.setPlaceholderText(TEXTS.get_text("placeholder.single_url"))
        self.start_page_spin = QtWidgets.QSpinBox()
        self.start_page_spin.setMinimum(1)
        self.start_page_spin.setMaximum(999999)
        self.end_page_spin = QtWidgets.QSpinBox()
        self.end_page_spin.setMinimum(1)
        self.end_page_spin.setMaximum(999999)
        self.page_range_widget = QtWidgets.QWidget()
        page_layout = QtWidgets.QHBoxLayout(self.page_range_widget)
        page_layout.setContentsMargins(0, 0, 0, 0)
        page_layout.addWidget(QtWidgets.QLabel(TEXTS.get_text("label.page_start")))
        page_layout.addWidget(self.start_page_spin)
        page_layout.addWidget(QtWidgets.QLabel(TEXTS.get_text("label.page_end")))
        page_layout.addWidget(self.end_page_spin)
        self.update_strategy_combo = QtWidgets.QComboBox()
        self.update_strategy_combo.addItem(TEXTS.get_text("strategy.only_new"), "only_new")
        self.update_strategy_combo.addItem(TEXTS.get_text("strategy.refresh_changed"), "refresh_changed")
        self.update_strategy_combo.addItem(TEXTS.get_text("strategy.full_refetch"), "full_refetch")
        task_layout.addRow(TEXTS.get_text("label.site"), self.site_combo)
        task_layout.addRow(TEXTS.get_text("label.task_name"), self.task_name_edit)
        task_layout.addRow(TEXTS.get_text("label.task_mode"), self.task_mode_combo)
        task_layout.addRow(TEXTS.get_text("label.single_url"), self.single_url_edit)
        task_layout.addRow(TEXTS.get_text("label.page_range"), self.page_range_widget)
        task_layout.addRow(TEXTS.get_text("label.update_strategy"), self.update_strategy_combo)
        self.update_strategy_hint_label = QtWidgets.QLabel(TEXTS.get_text("text.update_strategy_hint"))
        self.update_strategy_hint_label.setWordWrap(True)
        self.update_strategy_hint_label.setStyleSheet("color: #666;")
        task_layout.addRow("", self.update_strategy_hint_label)
        layout.addWidget(task_group)

        login_group = QtWidgets.QGroupBox(TEXTS.get_text("group.login_info"))
        login_layout = QtWidgets.QVBoxLayout(login_group)
        login_mode_row = QtWidgets.QHBoxLayout()
        login_mode_row.addWidget(QtWidgets.QLabel(TEXTS.get_text("label.login_mode")))
        self.login_mode_combo = QtWidgets.QComboBox()
        self.login_mode_combo.addItem(TEXTS.get_text("option.login_mode_account_password"), "account_password")
        self.login_mode_combo.addItem(TEXTS.get_text("option.login_mode_cookie"), "cookie")
        login_mode_row.addWidget(self.login_mode_combo)
        login_mode_row.addStretch()
        login_layout.addLayout(login_mode_row)
        self.login_hint_label = QtWidgets.QLabel()
        self.login_hint_label.setWordWrap(True)
        self.login_hint_label.setStyleSheet("color: #8a5a00;")
        self.login_hint_label.hide()
        login_layout.addWidget(self.login_hint_label)
        self.username_edit = QtWidgets.QLineEdit()
        self.username_edit.setPlaceholderText(TEXTS.get_text("placeholder.username"))
        self.password_edit = QtWidgets.QLineEdit()
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_edit.setPlaceholderText(TEXTS.get_text("placeholder.password"))
        self.cookie_edit = QtWidgets.QPlainTextEdit()
        self.cookie_edit.setPlaceholderText(TEXTS.get_text("placeholder.cookie"))
        self.cookie_edit.setFixedHeight(92)
        self.account_form = QtWidgets.QWidget()
        account_form_layout = QtWidgets.QFormLayout(self.account_form)
        account_form_layout.addRow(TEXTS.get_text("label.username"), self.username_edit)
        account_form_layout.addRow(TEXTS.get_text("label.password"), self.password_edit)
        self.cookie_form = QtWidgets.QWidget()
        cookie_form_layout = QtWidgets.QFormLayout(self.cookie_form)
        cookie_form_layout.addRow(TEXTS.get_text("label.cookie"), self.cookie_edit)
        self.login_stack = QtWidgets.QStackedWidget()
        self.login_stack.addWidget(self.account_form)
        self.login_stack.addWidget(self.cookie_form)
        login_layout.addWidget(self.login_stack)
        remember_row = QtWidgets.QHBoxLayout()
        self.remember_account_checkbox = QtWidgets.QCheckBox(TEXTS.get_text("label.remember_account"))
        self.remember_password_checkbox = QtWidgets.QCheckBox(TEXTS.get_text("label.remember_password"))
        remember_row.addWidget(self.remember_account_checkbox)
        remember_row.addWidget(self.remember_password_checkbox)
        remember_row.addStretch()
        login_layout.addLayout(remember_row)
        self.remember_password_hint_label = QtWidgets.QLabel(TEXTS.get_text("text.remember_password_hint"))
        self.remember_password_hint_label.setWordWrap(True)
        self.remember_password_hint_label.setStyleSheet("color: #666;")
        login_layout.addWidget(self.remember_password_hint_label)
        self.keychain_status_label = QtWidgets.QLabel(TEXTS.get_text("text.keychain_unavailable_hint"))
        self.keychain_status_label.setWordWrap(True)
        self.keychain_status_label.setStyleSheet("color: #8a5a00;")
        self.keychain_status_label.hide()
        login_layout.addWidget(self.keychain_status_label)
        layout.addWidget(login_group)

        settings_group = QtWidgets.QGroupBox(TEXTS.get_text("group.common_settings"))
        settings_layout = QtWidgets.QVBoxLayout(settings_group)
        settings_layout.setSpacing(8)
        purchase_row = QtWidgets.QHBoxLayout()
        self.purchase_checkbox = QtWidgets.QCheckBox(TEXTS.get_text("label.enable_purchase"))
        self.max_purchase_spin = QtWidgets.QSpinBox()
        self.max_purchase_spin.setMinimum(0)
        self.max_purchase_spin.setMaximum(999999)
        self.max_purchase_spin.setFixedWidth(120)
        purchase_row.addWidget(self.purchase_checkbox)
        purchase_row.addStretch()
        purchase_row.addWidget(QtWidgets.QLabel(TEXTS.get_text("label.purchase_limit")))
        purchase_row.addWidget(self.max_purchase_spin)
        settings_layout.addLayout(purchase_row)
        self.purchase_hint_label = QtWidgets.QLabel(TEXTS.get_text("text.purchase_hint"))
        self.purchase_hint_label.setWordWrap(True)
        self.purchase_hint_label.setStyleSheet("color: #666;")
        settings_layout.addWidget(self.purchase_hint_label)
        self.convert_hans_checkbox = QtWidgets.QCheckBox(TEXTS.get_text("label.convert_hans"))
        self.proxy_edit = QtWidgets.QLineEdit()
        self.proxy_edit.setPlaceholderText(TEXTS.get_text("placeholder.proxy_url"))
        self.convert_txt_checkbox = QtWidgets.QCheckBox(TEXTS.get_text("label.convert_txt"))
        switch_row = QtWidgets.QHBoxLayout()
        switch_row.addWidget(self.convert_hans_checkbox)
        switch_row.addWidget(self.convert_txt_checkbox)
        switch_row.addStretch()
        settings_layout.addLayout(switch_row)
        proxy_form = QtWidgets.QFormLayout()
        proxy_form.addRow(TEXTS.get_text("label.proxy_url"), self.proxy_edit)
        settings_layout.addLayout(proxy_form)
        self.proxy_hint_label = QtWidgets.QLabel(TEXTS.get_text("text.proxy_hint"))
        self.proxy_hint_label.setWordWrap(True)
        self.proxy_hint_label.setStyleSheet("color: #666;")
        settings_layout.addWidget(self.proxy_hint_label)
        layout.addWidget(settings_group)

        paths_group = QtWidgets.QGroupBox(TEXTS.get_text("group.paths_browser"))
        paths_layout = QtWidgets.QVBoxLayout(paths_group)
        paths_layout.setSpacing(8)
        path_form = QtWidgets.QFormLayout()
        self.output_root_edit = QtWidgets.QLineEdit()
        self.output_root_edit.setPlaceholderText(TEXTS.get_text("placeholder.output_root"))
        self.output_root_button = QtWidgets.QPushButton(TEXTS.get_text("button.browse"))
        output_row = QtWidgets.QWidget()
        output_layout = QtWidgets.QHBoxLayout(output_row)
        output_layout.setContentsMargins(0, 0, 0, 0)
        output_layout.addWidget(self.output_root_edit, 1)
        output_layout.addWidget(self.output_root_button)
        self.chrome_path_edit = QtWidgets.QLineEdit()
        self.chrome_path_edit.setPlaceholderText(TEXTS.get_text("placeholder.chrome_path"))
        self.chrome_path_button = QtWidgets.QPushButton(TEXTS.get_text("button.browse"))
        chrome_row = QtWidgets.QWidget()
        chrome_layout = QtWidgets.QHBoxLayout(chrome_row)
        chrome_layout.setContentsMargins(0, 0, 0, 0)
        chrome_layout.addWidget(self.chrome_path_edit, 1)
        chrome_layout.addWidget(self.chrome_path_button)
        path_form.addRow(TEXTS.get_text("label.output_root"), output_row)
        path_form.addRow(TEXTS.get_text("label.chrome_path"), chrome_row)
        paths_layout.addLayout(path_form)
        self.output_root_hint_label = QtWidgets.QLabel(TEXTS.get_text("text.output_root_hint"))
        self.output_root_hint_label.setWordWrap(True)
        self.output_root_hint_label.setStyleSheet("color: #666;")
        self.chrome_path_hint_label = QtWidgets.QLabel(TEXTS.get_text("text.chrome_path_hint"))
        self.chrome_path_hint_label.setWordWrap(True)
        self.chrome_path_hint_label.setStyleSheet("color: #666;")
        paths_layout.addWidget(self.output_root_hint_label)
        paths_layout.addWidget(self.chrome_path_hint_label)
        layout.addWidget(paths_group)

        tools_group = QtWidgets.QGroupBox(TEXTS.get_text("group.maintenance_tools"))
        tools_layout = QtWidgets.QVBoxLayout(tools_group)
        placeholder = QtWidgets.QLabel(TEXTS.get_text("text.maintenance_placeholder"))
        placeholder.setWordWrap(True)
        tools_layout.addWidget(placeholder)
        layout.addWidget(tools_group)

        layout.addStretch()
        return panel

    def _build_log_panel(self) -> QtWidgets.QWidget:
        panel = QtWidgets.QWidget()
        layout = QtWidgets.QVBoxLayout(panel)
        layout.setSpacing(12)

        button_row = QtWidgets.QHBoxLayout()
        self.start_button = QtWidgets.QPushButton(TEXTS.get_text("button.start_task"))
        self.open_output_button = QtWidgets.QPushButton(TEXTS.get_text("button.open_output_dir"))
        self.open_log_button = QtWidgets.QPushButton(TEXTS.get_text("button.open_log_dir"))
        button_row.addWidget(self.start_button)
        button_row.addWidget(self.open_output_button)
        button_row.addWidget(self.open_log_button)
        button_row.addStretch()
        layout.addLayout(button_row)

        status_group = QtWidgets.QGroupBox(TEXTS.get_text("group.run_status"))
        status_layout = QtWidgets.QFormLayout(status_group)
        self.status_value = QtWidgets.QLabel(TEXTS.get_text("status.idle"))
        self.site_value = QtWidgets.QLabel("-")
        self.book_value = QtWidgets.QLabel("-")
        self.chapter_value = QtWidgets.QLabel("-")
        status_layout.addRow(TEXTS.get_text("label.status_current"), self.status_value)
        status_layout.addRow(TEXTS.get_text("label.status_site"), self.site_value)
        status_layout.addRow(TEXTS.get_text("label.status_book"), self.book_value)
        status_layout.addRow(TEXTS.get_text("label.status_chapter"), self.chapter_value)
        layout.addWidget(status_group)

        log_group = QtWidgets.QGroupBox(TEXTS.get_text("group.run_log"))
        log_layout = QtWidgets.QVBoxLayout(log_group)
        self.log_hint_label = QtWidgets.QLabel(TEXTS.get_text("text.log_hint"))
        self.log_hint_label.setWordWrap(True)
        self.log_hint_label.setStyleSheet("color: #666;")
        log_layout.addWidget(self.log_hint_label)
        self.log_text = QtWidgets.QPlainTextEdit()
        self.log_text.setReadOnly(True)
        log_layout.addWidget(self.log_text)
        layout.addWidget(log_group, 1)
        return panel
