from __future__ import annotations

from PySide6 import QtCore, QtWidgets


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("lightnovel-pydownloader")
        self.resize(1180, 760)
        self._build_ui()

    def _build_ui(self):
        central = QtWidgets.QWidget()
        self.setCentralWidget(central)
        root_layout = QtWidgets.QHBoxLayout(central)
        root_layout.setContentsMargins(12, 12, 12, 12)
        root_layout.setSpacing(12)

        root_layout.addWidget(self._build_form_panel(), 1)
        root_layout.addWidget(self._build_log_panel(), 1)

    def _build_form_panel(self) -> QtWidgets.QWidget:
        panel = QtWidgets.QScrollArea()
        panel.setWidgetResizable(True)
        content = QtWidgets.QWidget()
        panel.setWidget(content)
        layout = QtWidgets.QVBoxLayout(content)
        layout.setSpacing(12)

        intro = QtWidgets.QLabel(
            "按顺序完成 3 步：选站点、填任务、填登录信息，然后点击“开始任务”。"
        )
        intro.setWordWrap(True)
        layout.addWidget(intro)

        task_group = QtWidgets.QGroupBox("任务设置")
        task_layout = QtWidgets.QFormLayout(task_group)
        self.task_form_layout = task_layout
        task_layout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.site_combo = QtWidgets.QComboBox()
        self.site_combo.addItems(["esj", "masiro", "lk", "yuri"])
        self.task_mode_combo = QtWidgets.QComboBox()
        self.task_mode_combo.addItem("单本链接", "single_link")
        self.task_mode_combo.addItem("收藏页抓取", "collection_page")
        self.task_mode_combo.addItem("页码范围抓取", "page_range")
        self.single_url_edit = QtWidgets.QLineEdit()
        self.single_url_edit.setPlaceholderText("粘贴小说详情页链接")
        self.start_page_spin = QtWidgets.QSpinBox()
        self.start_page_spin.setMinimum(1)
        self.start_page_spin.setMaximum(999999)
        self.end_page_spin = QtWidgets.QSpinBox()
        self.end_page_spin.setMinimum(1)
        self.end_page_spin.setMaximum(999999)
        self.page_range_widget = QtWidgets.QWidget()
        page_layout = QtWidgets.QHBoxLayout(self.page_range_widget)
        page_layout.setContentsMargins(0, 0, 0, 0)
        page_layout.addWidget(QtWidgets.QLabel("开始页"))
        page_layout.addWidget(self.start_page_spin)
        page_layout.addWidget(QtWidgets.QLabel("结束页"))
        page_layout.addWidget(self.end_page_spin)
        task_layout.addRow("站点", self.site_combo)
        task_layout.addRow("任务模式", self.task_mode_combo)
        task_layout.addRow("小说链接", self.single_url_edit)
        task_layout.addRow("页码范围", self.page_range_widget)
        layout.addWidget(task_group)

        login_group = QtWidgets.QGroupBox("登录信息")
        login_layout = QtWidgets.QVBoxLayout(login_group)
        login_mode_row = QtWidgets.QHBoxLayout()
        login_mode_row.addWidget(QtWidgets.QLabel("登录方式"))
        self.login_mode_combo = QtWidgets.QComboBox()
        self.login_mode_combo.addItem("账号密码", "account_password")
        self.login_mode_combo.addItem("Cookie", "cookie")
        login_mode_row.addWidget(self.login_mode_combo)
        login_mode_row.addStretch()
        login_layout.addLayout(login_mode_row)
        self.login_hint_label = QtWidgets.QLabel()
        self.login_hint_label.setWordWrap(True)
        self.login_hint_label.hide()
        login_layout.addWidget(self.login_hint_label)
        self.username_edit = QtWidgets.QLineEdit()
        self.password_edit = QtWidgets.QLineEdit()
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.cookie_edit = QtWidgets.QPlainTextEdit()
        self.cookie_edit.setPlaceholderText("粘贴 Cookie")
        self.cookie_edit.setFixedHeight(92)
        self.account_form = QtWidgets.QWidget()
        account_form_layout = QtWidgets.QFormLayout(self.account_form)
        account_form_layout.addRow("账号", self.username_edit)
        account_form_layout.addRow("密码", self.password_edit)
        self.cookie_form = QtWidgets.QWidget()
        cookie_form_layout = QtWidgets.QFormLayout(self.cookie_form)
        cookie_form_layout.addRow("Cookie", self.cookie_edit)
        self.login_stack = QtWidgets.QStackedWidget()
        self.login_stack.addWidget(self.account_form)
        self.login_stack.addWidget(self.cookie_form)
        login_layout.addWidget(self.login_stack)
        layout.addWidget(login_group)

        settings_group = QtWidgets.QGroupBox("常用设置")
        settings_layout = QtWidgets.QFormLayout(settings_group)
        self.purchase_checkbox = QtWidgets.QCheckBox("允许购买付费章节")
        self.max_purchase_spin = QtWidgets.QSpinBox()
        self.max_purchase_spin.setMinimum(0)
        self.max_purchase_spin.setMaximum(999999)
        self.convert_hans_checkbox = QtWidgets.QCheckBox("繁体转简体")
        self.proxy_edit = QtWidgets.QLineEdit()
        self.proxy_edit.setPlaceholderText("http://127.0.0.1:1081")
        self.convert_txt_checkbox = QtWidgets.QCheckBox("同时导出 TXT")
        settings_layout.addRow("", self.purchase_checkbox)
        settings_layout.addRow("购买上限", self.max_purchase_spin)
        settings_layout.addRow("", self.convert_hans_checkbox)
        settings_layout.addRow("代理", self.proxy_edit)
        settings_layout.addRow("", self.convert_txt_checkbox)
        layout.addWidget(settings_group)

        tools_group = QtWidgets.QGroupBox("维护工具")
        tools_layout = QtWidgets.QVBoxLayout(tools_group)
        placeholder = QtWidgets.QLabel("这一块会在第二轮接通，第一轮先保留结构，不执行实际维护操作。")
        placeholder.setWordWrap(True)
        tools_layout.addWidget(placeholder)
        layout.addWidget(tools_group)

        layout.addStretch()
        return panel

    def _build_log_panel(self) -> QtWidgets.QWidget:
        panel = QtWidgets.QWidget()
        layout = QtWidgets.QVBoxLayout(panel)
        layout.setSpacing(12)

        button_row = QtWidgets.QHBoxLayout()
        self.start_button = QtWidgets.QPushButton("开始任务")
        self.open_output_button = QtWidgets.QPushButton("打开输出目录")
        self.open_log_button = QtWidgets.QPushButton("打开日志目录")
        button_row.addWidget(self.start_button)
        button_row.addWidget(self.open_output_button)
        button_row.addWidget(self.open_log_button)
        button_row.addStretch()
        layout.addLayout(button_row)

        status_group = QtWidgets.QGroupBox("运行状态")
        status_layout = QtWidgets.QFormLayout(status_group)
        self.status_value = QtWidgets.QLabel("空闲")
        self.site_value = QtWidgets.QLabel("-")
        self.book_value = QtWidgets.QLabel("-")
        self.chapter_value = QtWidgets.QLabel("-")
        status_layout.addRow("当前状态", self.status_value)
        status_layout.addRow("当前站点", self.site_value)
        status_layout.addRow("当前书籍", self.book_value)
        status_layout.addRow("当前章节", self.chapter_value)
        layout.addWidget(status_group)

        log_group = QtWidgets.QGroupBox("运行日志")
        log_layout = QtWidgets.QVBoxLayout(log_group)
        self.log_text = QtWidgets.QPlainTextEdit()
        self.log_text.setReadOnly(True)
        log_layout.addWidget(self.log_text)
        layout.addWidget(log_group, 1)
        return panel
